@email=example@example.com
@password=NewPassword!123

###
# @name session
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "responseType": "json"
}

###
# @name logout
# @ref session
POST {{host}}/auth/logout HTTP/1.1
Cookie: accessToken={{session.data.accessToken}}
Cookie: refreshToken={{session.data.refreshToken}}


###
# @name refresh
# @ref session
POST {{host}}/auth/refresh-token HTTP/1.1
Cookie: refreshToken={{session.data.refreshToken}}


###
# @name forgotPassword
POST {{host}}/auth/forgot-password HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}"
}

###
# @name resetPassword
@resetToken=fc8b5dfe-cd0b-4fd7-86d8-d6496fa083d7
@newPassword=NewPassword!123
POST {{host}}/auth/reset-password HTTP/1.1
Content-Type: application/json

{
  "newPassword": "{{newPassword}}",
  "resetToken": "{{resetToken}}"
}